name: Deploy EC2

on:
workflow_dispatch:
inputs:
environment:
description: "Choose environment"
required: true
default: "dev"
type: choice
options:
- dev
- qa
- prod
base_name:
description: "Base server name"
required: true
default: "my-server"

jobs:
deploy:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout
    uses: actions/checkout@v3

  - name: AWS Credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ap-south-1

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v2

  - name: Init
    working-directory: env/${{ github.event.inputs.environment }}
    run: terraform init

  - name: Plan
    working-directory: env/${{ github.event.inputs.environment }}
    run: |
      echo "Deploy plan for ${{ github.event.inputs.environment }}"
      terraform plan -var="base_name=${{ github.event.inputs.base_name }}"

  - name: Apply
    working-directory: env/${{ github.event.inputs.environment }}
    run: |
      echo "Deploying ${{ github.event.inputs.environment }}"
      terraform apply -auto-approve -var="base_name=${{ github.event.inputs.base_name }}"
```
