name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod
      base_name:
        description: "Base server name"
        required: true
        default: "my-server"

jobs:
  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set Environment Variables
        run: |
          echo "ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "BASE_NAME=${{ github.event.inputs.base_name }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Select Workspace
        run: |
          terraform workspace select $ENV || terraform workspace new $ENV

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="environment=$ENV" \
            -var="base_name=$BASE_NAME"

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="environment=$ENV" \
            -var="base_name=$BASE_NAME"