name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod
          - all

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Destroy
        run: |
          if [ "${{ github.event.inputs.environment }}" == "all" ]; then
            ENVS="dev qa prod"
          else
            ENVS="${{ github.event.inputs.environment }}"
          fi

          for ENV in $ENVS; do
            echo "Destroying $ENV"

            terraform workspace select $ENV || continue

            terraform destroy -auto-approve \
              -var="environment=$ENV"
          done