name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment to destroy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod
          - all

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev, qa, prod]

    # Run all when "all" is selected, otherwise only selected env
    if: |
      github.event.inputs.environment == 'all' ||
      github.event.inputs.environment == matrix.env

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set Environment Variable
        run: echo "ENV=${{ matrix.env }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Select Workspace
        run: |
          terraform workspace select $ENV || echo "Workspace not found, skipping..."

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve \
            -var="environment=$ENV"